spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ugg
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kakao:
    auth:
      client: ${KAKAO_CLIENT}
      redirect: ${KAKAO_REDIRECT}

jwt:
  expiration_time: 86400000
  secret: ${JWT_SECRET}



server:
  port: 8080
